### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jinhzhou** [vs66388/hyprland#1]
Hi! I am trying to install hyprland and I found your guide from google. I am a newbie to both arch linux and to hyprland. 

I copied through every step but got stuck on the installation step. I created a Downloads folder and cloned your repo using git.
I could not go through the last step  "cp .config/ ~/.config/"
terminal kept outputting: -r not specified; omitting directory '.config/'

when i typed ls -la while I was in the downloads terminal I got:
.
..
.config
hyprland

How can i solve this issue?

**Comment by jinhzhou** [comment]
the yellow bar has dissappeared

i kept using the cd command until i found your .config file and then i used cp path path (the one on the yellow bar)

but nothing else is synced up, my waybar and wallpaper do not look like yours.

**Comment by jinhzhou** [comment]
i forgot to mention that there was a yellow bar that said i was using an autogenerated version of hyprland

**Comment by vs66388** [comment]
ok so listen its not your fault first of all you are new so its bound to happen first have you installed all the dependencies 👍🏼 if youve downloaded nemo go ahead and open it using super + f and [ress ctrl + h to show hidden file 
go to downloads locate .config folder in it open it copy all its content then go to your home directory then into .config and then paste the content thier 
it should reload automatically and if wallpaper dosnt appear go into .config into your home folder rename your loved wallpaper to sunset go thier you go message me for any other issue here

**Comment by vs66388** [comment]
it is bound to happen when you do it have you installed all the depedencies in par section important 1 is called eww-wayland its the bar i am using so wayland wont work and please mention if you are using arch

**Comment by vs66388** [comment]
> r .config file and then i

**Comment by vs66388** [comment]
> Hi! I am trying to install hyprland and I found your guide from google. I am a newbie to both arch linux and to hyprland.
> 
> I copied through every step but got stuck on the installation step. I created a Downloads folder and cloned your repo using git. I could not go through the last step "cp .config/ ~/.config/" terminal kept outputting: -r not specified; omitting directory '.config/'
> 
> when i typed ls -la while I was in the downloads terminal I got: . .. .config hyprland
> 
> How can i solve this issue?

and if you have an issue thier is an new updated version please refer to [Updated version](https://github.com/vs66388/Hypr-uwu.git) this i would recommend using this one ill help you along theway

**Comment by jinhzhou** [comment]
Hi!! thank you so much for your reply and all your help! I apoligize for not including some important facts about my system. I don't beleive I installed eww-wayland. And thank you for linking the new guide (I should have looked for it before clicking the first hyprland link I saw). I can't express how thankful I am to have someone by my side as I try to make this all work out so thanks again!! 

I will be going to sleep soon. Tomorrow, I will definitely check out the new repo and follow through it :D (I'll update you on how it goes!!)

**Comment by vs66388** [comment]
Ok sir im pleased to help you this guide was a lityle rough around edges and new one works fine as many people use it as daily driver on thier laptops and desktops from many i mean 8 its a little rough around edges but ill be updating it soon as well know issues are bluetooth on and off from notifu center and 1 blank icon thats all
